spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET:your_default_development_secret_key_minimum_32_chars}
    accessTokenExpiration: 300 #5min
    refreshTokenExpiration: 604800 #7d
